"""Descricoes breves em PT-BR dos controles ISO 27002:2022 e ISO 27701 para questionarios de auditoria."""

DESCRIPTIONS_27002: dict[str, str] = {
    "5.1": "Definir, aprovar, publicar e revisar politicas de seguranca da informacao alinhadas aos objetivos da organizacao. As politicas devem ser comunicadas e exigir conformidade de colaboradores e partes relevantes.",
    "5.2": "Atribuir e documentar funcoes e responsabilidades de seguranca da informacao de forma clara, incluindo segregacao entre gestao e operacao quando aplicavel. Garantir que as responsabilidades sejam conhecidas e cumpridas.",
    "5.3": "Separar funcoes conflitantes para reduzir risco de fraude, erro ou bypass de controles. Evitar que uma mesma pessoa execute etapas incompativeis sem supervisao ou compensacao adequada.",
    "5.4": "Exigir que a direcao demonstre lideranca e compromisso com a seguranca da informacao, incluindo recursos e apoio a melhorias. A alta gestao deve promover cultura de seguranca e responsabilizacao.",
    "5.5": "Manter contatos apropriados com autoridades regulatorias, policiais e de emergencia relevantes. Facilitar comunicacao rapida em incidentes e cumprimento de obrigacoes legais.",
    "5.6": "Participar de grupos de interesse, foruns e associacoes de seguranca para compartilhar informacoes e boas praticas. Aproveitar inteligencia coletiva sobre ameacas e tendencias do setor.",
    "5.7": "Coletar e analisar informacoes sobre ameacas para orientar avaliacao de riscos e controles. Integrar inteligencia de ameacas ao planejamento e resposta de seguranca.",
    "5.8": "Incorporar requisitos de seguranca da informacao desde o inicio de projetos e mudancas. Avaliar riscos de SI em entregas, recursos e cronogramas de projetos.",
    "5.9": "Manter inventario atualizado de informacoes e ativos associados, com proprietarios e classificacao. O inventario sustenta gestao de riscos, acesso e ciclo de vida dos ativos.",
    "5.10": "Definir regras de uso aceitavel para informacoes e ativos, incluindo uso pessoal e restricoes. Comunicar expectativas e consequencias de uso indevido.",
    "5.11": "Garantir devolucao de ativos organizacionais ao encerrar contrato, mudanca de funcao ou desligamento. Incluir equipamentos, credenciais, documentos e dados sob custodia do colaborador.",
    "5.12": "Classificar informacoes conforme necessidade de protecao legal, valor e criticidade. A classificacao orienta controles de acesso, rotulagem e tratamento.",
    "5.13": "Rotular informacao de acordo com o esquema de classificacao adotado, em meios fisicos e digitais. Facilitar identificacao e manuseio correto por quem acessa os dados.",
    "5.14": "Proteger informacao em transferencias internas e externas por acordos, criptografia ou canais seguros. Considerar tipo de meio, destinatario e classificacao da informacao.",
    "5.15": "Estabelecer politica e regras de controle de acesso baseadas em necessidade de negocio e principio do menor privilegio. Cobrir usuarios, sistemas, redes e aplicacoes.",
    "5.16": "Gerenciar ciclo de vida de identidades de usuarios e contas de servico, incluindo provisionamento e desprovisionamento. Vincular identidades a pessoas ou entidades autorizadas.",
    "5.17": "Proteger credenciais e demais informacoes de autenticacao contra divulgacao e uso indevido. Definir requisitos de qualidade, distribuicao, armazenamento e revogacao.",
    "5.18": "Conceder, revisar e revogar direitos de acesso de forma formal e periodica. Garantir que permissoes reflitam funcao atual e sejam removidas quando nao mais necessarias.",
    "5.19": "Identificar e tratar riscos de seguranca da informacao em relacionamentos com fornecedores. Avaliar capacidade de fornecedores antes e durante a contratacao.",
    "5.20": "Incluir requisitos de seguranca da informacao em contratos e acordos com fornecedores. Cobrir confidencialidade, conformidade, auditoria e tratamento de incidentes.",
    "5.21": "Gerenciar riscos de seguranca na cadeia de fornecimento de produtos e servicos de TIC. Considerar componentes, atualizacoes, integridade e origem dos fornecedores.",
    "5.22": "Monitorar, revisar e gerenciar mudancas nos servicos prestados por fornecedores. Avaliar desempenho de seguranca e reagir a desvios ou incidentes.",
    "5.23": "Definir requisitos e responsabilidades de seguranca no uso de servicos em nuvem. Esclarecer modelo de responsabilidade compartilhada e controles do provedor versus cliente.",
    "5.24": "Planejar e preparar processos, equipes e ferramentas para gestao de incidentes de seguranca da informacao. Definir papeis, comunicacao e criterios de escalonamento.",
    "5.25": "Avaliar eventos de seguranca para decidir se constituem incidentes e priorizar resposta. Registrar eventos e correlacionar indicadores suspeitos.",
    "5.26": "Responder a incidentes de forma estruturada para conter, erradicar e recuperar servicos. Preservar evidencias e comunicar partes interessadas conforme plano.",
    "5.27": "Analisar incidentes e licoes aprendidas para melhorar controles e preparacao. Atualizar procedimentos, treinamento e avaliacao de riscos com base nos achados.",
    "5.28": "Definir procedimentos para coleta e preservacao de evidencias digitais e fisicas. Garantir cadeia de custodia e admissibilidade quando necessario para investigacao ou acao legal.",
    "5.29": "Manter seguranca da informacao durante interrupcoes operacionais ou de negocio. Aplicar controles alternativos ou reforcados conforme plano de continuidade.",
    "5.30": "Garantir prontidao de TIC para suportar continuidade de negocios nos tempos e niveis definidos. Incluir redundancia, backup, recuperacao e testes periodicos.",
    "5.31": "Identificar e cumprir requisitos legais, estatutarios, regulatorios e contratuais aplicaveis a SI. Manter registro de obrigacoes e revisar mudancas na legislacao.",
    "5.32": "Proteger direitos de propriedade intelectual e uso licenciado de software e conteudo. Evitar copia ou distribuicao nao autorizada de materiais protegidos.",
    "5.33": "Proteger registros contra perda, destruicao, falsificacao e acesso nao autorizado. Definir retencao, armazenamento e descarte conforme requisitos legais e de negocio.",
    "5.34": "Cumprir requisitos de privacidade e protecao de dados pessoais (PII) aplicaveis. Alinhar tratamento de PII a politicas, consentimento e direitos dos titulares.",
    "5.35": "Realizar analises criticas independentes da abordagem de seguranca da informacao em intervalos planejados. Avaliar eficacia do SGSI e oportunidades de melhoria.",
    "5.36": "Verificar conformidade com politicas, procedimentos e normas de seguranca da informacao. Tratar desvios e reforcar accountability por area ou processo.",
    "5.37": "Documentar e manter procedimentos operacionais para atividades criticas de SI. Garantir que operadores sigam instrucoes consistentes e atualizadas.",
    "6.1": "Verificar antecedentes de candidatos antes da contratacao, proporcionais ao cargo e acesso a informacoes. Incluir referencias e checagens legais quando exigido.",
    "6.2": "Incluir responsabilidades de seguranca da informacao nos contratos de trabalho e termos de colaboradores. Formalizar deveres de confidencialidade e uso aceitavel desde o inicio.",
    "6.3": "Promover conscientizacao, educacao e treinamento continuos em seguranca da informacao. Adequar conteudo ao perfil e atualizar conforme ameacas e politicas.",
    "6.4": "Aplicar processo disciplinar formal para violacoes da politica de seguranca da informacao. Garantir proporcionalidade e registro das medidas adotadas.",
    "6.5": "Gerenciar responsabilidades de seguranca apos mudanca ou termino de emprego, incluindo revogacao de acessos. Reforcar obrigacoes de confidencialidade apos desligamento.",
    "6.6": "Exigir acordos de confidencialidade ou nao divulgacao quando aplicavel a colaboradores e terceiros. Cobrir escopo, duracao e consequencias de violacao.",
    "6.7": "Definir requisitos de seguranca para trabalho remoto, incluindo acesso, equipamento e ambiente fisico. Orientar uso seguro de redes e protecao de informacao fora das instalacoes.",
    "6.8": "Estimular e facilitar relato oportuno de eventos e fraquezas de seguranca da informacao. Garantir canal conhecido e tratamento sem retaliacao indevida ao relator.",
    "7.1": "Definir e proteger perimetros fisicos de areas que contem informacoes e ativos sensíveis. Usar barreiras, controle de entrada e sinalizacao adequada.",
    "7.2": "Controlar entrada fisica em instalacoes e areas seguras por autorizacao e registro. Gerenciar visitantes, credenciais e acesso temporario.",
    "7.3": "Proteger escritorios, salas e instalacoes contra acesso nao autorizado, danos e interferencia. Considerar localizacao, blindagem e isolamento de areas criticas.",
    "7.4": "Monitorar areas fisicas por pessoal, alarmes ou CCTV conforme avaliacao de risco. Registrar e revisar eventos de seguranca fisica.",
    "7.5": "Proteger instalacoes contra ameacas fisicas e ambientais como incendio, inundacao, vandalismo e falha de energia. Implementar detectores, supressao e redundancia quando necessario.",
    "7.6": "Estabelecer regras e controles para trabalho em areas seguras, incluindo conhecimento das atividades e restricoes. Limitar atividades nao autorizadas nessas areas.",
    "7.7": "Aplicar politica de mesa limpa e tela limpa para reduzir exposicao de informacao sensivel. Bloquear estacoes e armazenar documentos quando ausente.",
    "7.8": "Posicionar e proteger equipamentos contra ameacas ambientais e acesso nao autorizado. Proteger cabos, energia e suporte de processamento.",
    "7.9": "Proteger ativos utilizados fora das instalacoes, incluindo dispositivos moveis e midias. Definir responsabilidades do usuario e medidas como criptografia e bloqueio.",
    "7.10": "Gerenciar ciclo de vida de midias de armazenamento, incluindo manuseio, transporte e descarte seguro. Evitar vazamento de dados remanescentes em midias reutilizadas.",
    "7.11": "Proteger instalacoes de energia, HVAC, comunicacoes e outros servicos de suporte contra falha ou sabotagem. Monitorar e manter conformidade com requisitos de SI.",
    "7.12": "Proteger cabeamento de energia e telecomunicacoes contra interceptacao, dano ou indisponibilidade. Separar cabos de dados de fontes de interferencia quando possivel.",
    "7.13": "Realizar manutencao de equipamentos conforme especificacoes do fabricante e politica interna. Autorizar pessoal de manutencao e supervisionar trabalhos em equipamentos sensiveis.",
    "7.14": "Descartar ou reutilizar equipamentos de forma segura, removendo dados e licencas. Verificar destruicao ou sanitizacao de midias antes do descarte.",
    "8.1": "Proteger dispositivos finais de usuarios contra ameacas e uso indevido por politicas e ferramentas. Incluir patch, antimalware, criptografia e restricao de software.",
    "8.2": "Restringir e gerenciar contas e direitos de acesso privilegiado com aprovacao e monitoramento. Minimizar privilegios e revisar uso periodicamente.",
    "8.3": "Restringir acesso a informacao e funcoes de sistemas conforme politica de controle de acesso. Aplicar mecanismos tecnicos alinhados a classificacao e necessidade de negocio.",
    "8.4": "Controlar acesso ao codigo-fonte, bibliotecas e ferramentas de desenvolvimento. Evitar alteracoes nao autorizadas e vazamento de propriedade intelectual.",
    "8.5": "Implementar mecanismos de autenticacao segura proporcionais ao risco, incluindo MFA quando adequado. Proteger sessoes e bloquear tentativas de acesso indevido.",
    "8.6": "Monitorar e projetar capacidade de recursos de processamento, armazenamento e rede. Planejar expansao para evitar degradacao ou indisponibilidade por sobrecarga.",
    "8.7": "Proteger contra malware com deteccao, prevencao e recuperacao em endpoints e servidores. Atualizar assinaturas e restringir execucao nao autorizada.",
    "8.8": "Identificar, avaliar e tratar vulnerabilidades tecnicas em sistemas e aplicacoes. Aplicar patches ou compensacoes em prazos alinhados ao risco.",
    "8.9": "Estabelecer, documentar e monitorar configuracoes seguras de hardware e software. Controlar mudancas e usar linhas de base endurecidas.",
    "8.10": "Excluir informacao de sistemas e midias quando nao mais necessaria, de forma irreversivel quando exigido. Registrar exclusoes sensiveis e validar eficacia.",
    "8.11": "Aplicar mascaramento de dados em exibicoes, relatorios e interfaces para limitar exposicao de PII ou dados sensiveis. Usar tecnicas adequadas ao contexto de uso.",
    "8.12": "Prevenir vazamento de dados por monitoramento, DLP e restricoes de exportacao ou compartilhamento. Cobrir e-mail, armazenamento, impressao e canais de saida.",
    "8.13": "Realizar backups de informacao e software conforme politica, testando restauracao periodicamente. Proteger backups contra acesso nao autorizado e perda.",
    "8.14": "Prover redundancia de instalacoes de processamento para atender requisitos de disponibilidade. Alinhar a objetivos de continuidade e recuperacao de desastres.",
    "8.15": "Registrar eventos relevantes de seguranca e operacao, protegendo logs contra alteracao. Definir retencao, sincronizacao de tempo e analise de registros.",
    "8.16": "Monitorar redes, sistemas e aplicacoes para detectar comportamento anomalo e incidentes. Integrar alertas a processos de resposta e gestao de vulnerabilidades.",
    "8.17": "Sincronizar relogios de sistemas com fonte confiavel para correlacao de eventos e investigacoes. Aplicar em todos os sistemas que geram registros de auditoria.",
    "8.18": "Restringir e controlar uso de programas utilitarios que podem contornar controles de sistema. Limitar a administradores autorizados e registrar uso.",
    "8.19": "Controlar instalacao de software em sistemas operacionais por politica e ferramentas de gestao. Permitir apenas software aprovado e licenciado.",
    "8.20": "Proteger redes e dispositivos de rede contra ameacas e acesso nao autorizado. Aplicar segmentacao, filtragem e endurecimento de equipamentos.",
    "8.21": "Proteger servicos de rede e aplicacoes expostos, incluindo autenticacao e criptografia. Gerenciar configuracoes de servicos e desativar funcoes desnecessarias.",
    "8.22": "Segmentar redes para isolar grupos de servicos, usuarios e sistemas conforme risco. Limitar propagacao de incidentes entre segmentos.",
    "8.23": "Filtrar acesso a sites e conteudo web malicioso ou nao autorizado. Aplicar listas, categorias e inspecao conforme politica de uso aceitavel.",
    "8.24": "Usar criptografia adequada para proteger confidencialidade e integridade da informacao em repouso e em transito. Gerenciar chaves e algoritmos conforme boas praticas.",
    "8.25": "Integrar seguranca em todas as fases do ciclo de vida de desenvolvimento de sistemas e software. Definir requisitos, modelagem de ameacas e revisoes de seguranca.",
    "8.26": "Especificar e validar requisitos de seguranca em aplicacoes novas e alteradas. Considerar autenticacao, autorizacao, entrada de dados e protecao de sessao.",
    "8.27": "Aplicar principios de arquitetura e engenharia segura em projetos de sistemas. Usar padroes, defesa em profundidade e minimizacao de superficie de ataque.",
    "8.28": "Adotar praticas de codificacao segura e revisao de codigo para reduzir vulnerabilidades. Treinar desenvolvedores e usar ferramentas de analise estatica quando aplicavel.",
    "8.29": "Executar testes de seguranca durante desenvolvimento e aceitacao antes de producao. Incluir testes funcionais, penetracao ou SAST/DAST conforme risco.",
    "8.30": "Direcionar e supervisionar desenvolvimento terceirizado quanto a requisitos de seguranca e entregaveis. Exigir conformidade contratual e evidencias de testes.",
    "8.31": "Separar ambientes de desenvolvimento, teste e producao para evitar impacto nao autorizado em producao. Controlar promocao de codigo e dados entre ambientes.",
    "8.32": "Gerenciar mudancas em sistemas e infraestrutura por processo formal com avaliacao de impacto e aprovacao. Registrar, testar e reverter mudancas quando necessario.",
    "8.33": "Proteger dados de teste, evitando uso de dados reais sensiveis sem autorizacao e mascaramento. Eliminar ou proteger dados de teste apos o uso.",
    "8.34": "Planejar e restringir testes de auditoria para nao afetar disponibilidade ou integridade de sistemas em producao. Coordenar com responsaveis e monitorar atividades de teste.",
}

DESCRIPTIONS_27701: dict[str, str] = {
    "A1.1": "Estabelecer politica de privacidade e protecao de PII alinhada ao papel de controlador e requisitos legais. Comunicar compromissos e revisar periodicamente.",
    "A1.2": "Definir papeis e responsabilidades para privacidade e tratamento de PII em toda a organizacao. Garantir accountability e interfaces com DPO ou equivalente quando aplicavel.",
    "A1.3": "Incorporar privacidade desde a concepcao e por padrao em processos, sistemas e produtos. Minimizar coleta e maximizar protecao por desenho.",
    "A1.4": "Manter inventario das atividades de tratamento de PII, finalidades, categorias de dados e destinatarios. Base para transparencia, RIPD e demonstracao de conformidade.",
    "A1.5": "Identificar e documentar base legal para cada tratamento e gerenciar consentimento quando exigido. Permitir revogacao e registro de preferencias do titular.",
    "A1.6": "Limitar tratamento de PII as finalidades determinadas, explicitas e legitimas. Evitar uso secundario incompativel sem nova base legal ou consentimento.",
    "A1.7": "Coletar e manter apenas PII adequada, relevante e limitada ao necessario para a finalidade. Revisar periodicamente a necessidade de campos e registros.",
    "A1.8": "Manter PII exata e atualizada, corrigindo ou completando dados quando identificadas imprecisoes. Oferecer meios para titulares atualizarem informacoes.",
    "A1.9": "Definir prazos de retencao e procedimentos seguros de descarte ou anonimizacao de PII. Nao reter dados alem do necessario para a finalidade ou obrigacao legal.",
    "A1.10": "Atender direitos dos titulares como acesso, retificacao, exclusao, portabilidade e oposicao nos prazos legais. Documentar solicitacoes e respostas.",
    "A1.11": "Realizar avaliacao de impacto a protecao de dados (RIPD/AIPD) quando o tratamento apresentar alto risco. Implementar medidas de mitigacao e consultar autoridade se exigido.",
    "A1.12": "Formalizar contratos com operadores de PII com clausulas de seguranca, subcontratacao e assistencia. Monitorar conformidade dos operadores contratados.",
    "A1.13": "Garantir transferencias internacionais de PII apenas com salvaguardas adequadas e base legal. Documentar mecanismos como clausulas padrao ou decisoes de adequacao.",
    "A1.14": "Notificar autoridades e titulares de incidentes envolvendo PII conforme prazos e criterios legais. Integrar com gestao de incidentes de seguranca.",
    "A1.15": "Promover conscientizacao em privacidade para colaboradores que tratam PII. Atualizar treinamento conforme mudancas regulatorias e processos.",
    "A1.16": "Documentar obrigacoes do controlador perante titulares e lei aplicavel de forma acessivel. Manter registros que demonstrem accountability.",
    "A1.17": "Definir arranjos claros entre controladores conjuntos sobre responsabilidades e comunicacao com titulares. Formalizar em acordo acessivel ao titular.",
    "A1.18": "Limitar coleta de PII ao minimo necessario no momento da obtencao, por meios legais e transparentes. Evitar coleta excessiva ou enganosa.",
    "A1.19": "Fornecer aviso de privacidade claro ao titular no momento da coleta, com finalidades, bases legais e direitos. Atualizar avisos quando o tratamento mudar.",
    "A1.20": "Estabelecer criterios para selecao de operadores quanto a capacidade de proteger PII. Avaliar antes da contratacao e revisar periodicamente.",
    "A1.21": "Controlar e autorizar suboperadores que tratam PII em nome do controlador. Manter lista atualizada e garantir obrigacoes contratuais equivalentes.",
    "A1.22": "Manter registro das atividades de tratamento conforme exigido pela legislacao aplicavel. Incluir finalidades, categorias, destinatarios e transferencias.",
    "A1.23": "Gerenciar decisoes automatizadas e perfilamento com transparencia e direito de contestacao quando aplicavel. Avaliar impactos e bases legais especificas.",
    "A1.24": "Tratar PII em marketing e comunicacoes com consentimento ou base legal adequada e opt-out. Respeitar preferencias e registros de consentimento.",
    "A1.25": "Informar e obter consentimento para cookies e tecnologias similares conforme regulacao. Permitir gestao de preferencias e registro de escolhas.",
    "A2.1": "Seguir instrucoes documentadas do controlador sobre tratamento de PII e limites de finalidade. Nao tratar alem do contratado sem autorizacao.",
    "A2.2": "Garantir confidencialidade de pessoas autorizadas a tratar PII por contrato e treinamento. Aplicar obrigacoes mesmo apos termino do relacionamento.",
    "A2.3": "Implementar medidas de seguranca do tratamento proporcionais ao risco, alinhadas ao SGSI. Proteger PII contra acesso, perda ou divulgacao nao autorizados.",
    "A2.4": "Obter autorizacao previa do controlador para subcontratar tratamento de PII. Informar identidade de suboperadores e manter cadeia contratual.",
    "A2.5": "Auxiliar o controlador no atendimento a direitos dos titulares dentro dos prazos acordados. Fornecer informacoes e ferramentas necessarias a resposta.",
    "A2.6": "Excluir ou devolver PII ao controlador ao termino do contrato, salvo obrigacao legal de retencao. Certificar destruicao segura quando aplicavel.",
    "A2.7": "Disponibilizar ao controlador informacoes necessarias para demonstrar conformidade com privacidade e contrato. Incluir relatorios e evidencias sob solicitacao.",
    "A2.8": "Permitir auditorias e inspecoes pelo controlador ou auditor autorizado, com limites razoaveis. Cooperar na verificacao de controles de tratamento.",
    "A2.9": "Notificar o controlador sem demora indevida sobre incidentes de PII que afetem dados sob tratamento. Fornecer detalhes para avaliacao de notificacao regulatoria.",
    "A2.10": "Tratar localizacao e transferencia internacional de PII apenas conforme instrucoes e salvaguardas do controlador. Documentar paises e mecanismos aplicados.",
    "A2.11": "Gerenciar acessos de pessoas do operador ao PII do controlador com principio do menor privilegio. Revisar contas e revogar acessos desnecessarios.",
    "A2.12": "Segregar PII de diferentes controladores para evitar mistura ou uso cruzado indevido. Aplicar separacao logica ou fisica conforme arquitetura.",
    "A2.13": "Monitorar cumprimento das obrigacoes contratuais de tratamento e medidas de seguranca acordadas. Reportar desvios ao controlador.",
    "A2.14": "Retener PII do controlador apenas pelo periodo necessario ao servico ou instrucao contratual. Nao usar dados para fins proprios do operador.",
    "A2.15": "Restringir uso de PII as finalidades e instrucoes do controlador, sem tratamento adicional nao autorizado. Bloquear usos secundarios nao contratados.",
    "A2.16": "Gerenciar mudancas no tratamento que afetem PII com avaliacao de impacto e comunicacao ao controlador. Obter aprovacao antes de alteracoes materiais.",
    "A2.17": "Garantir continuidade do tratamento de PII conforme requisitos de continuidade acordados com o controlador. Incluir recuperacao e comunicacao em interrupcoes.",
    "A2.18": "Capacitar pessoas do operador que tratam PII em privacidade e seguranca do tratamento. Atualizar conforme mudancas de processo ou legislacao.",
    "A2.19": "Encaminhar ao controlador solicitacoes de titulares recebidas diretamente pelo operador, sem responder fora de instrucao. Registrar e rastrear prazos.",
    "A2.20": "Manter registro das operacoes de tratamento realizadas em nome de cada controlador. Suportar demonstracao de conformidade e auditoria.",
    "A2.21": "Aplicar criptografia e pseudonimizacao no tratamento de PII conforme instrucoes e boas praticas. Proteger dados em repouso, transito e backup.",
    "A2.22": "Realizar testes e avaliacoes periodicas de seguranca dos sistemas que tratam PII. Corrigir vulnerabilidades e reportar resultados relevantes ao controlador.",
    "A2.23": "Encerrar contratos de tratamento com devolucao ou destruicao segura de PII e revogacao de acessos. Documentar encerramento e certificacoes quando exigidas.",
    "A2.24": "Cooperar com autoridades de protecao de dados conforme orientacao do controlador e lei aplicavel. Fornecer informacoes solicitadas dentro do escopo contratual.",
}
